modules/advance/models/Record.php
<?php

use Illuminate\Support\Facades\Config;
use Jenssegers\Date\Date;
use Atlantis\Detail\Model\Record as BaseRecord;


class Record extends BaseRecord {

    /** @var array Guard list */
    protected $guarded = array('uuid','message','user','guardian','guarantor','detail','url_update','transaction','application_location_name','created_when','updated_when');

    /** @var array Attribute append */
    protected $appends = array('url_update','application_location_name','created_when','updated_when');


    protected static function boot()
    {
        parent::boot();

        static::deleting(function($record){
            $record->conversation()->delete();
        });
    }


    public function user(){
        return $this->belongsTo('User');
    }


    public function guardian(){
        return $this->hasOne('People','id','guardian_id');
    }


    public function guarantor(){
        return $this->hasOne('People','id','guarantor_id');
    }


    public function transaction(){
        return $this->hasOne('Modules\Advance\Transaction','id','payment_id');
    }


    public function conversation(){
        return $this->hasMany('Conversation','subject');
    }
    /**
     * Status Attribute - Get
     *
     * @param $value
     * @return mixed
     */
    public function getStatusAttribute($value){
        $status = $this->detail->workflows('resource.status')[$value];

        #i: Save original value
        $status['raw'] = $value;

        return $status;
    }


    /**
     * Status Attribute - Set
     *
     * @param $value
     */
    public function setStatusAttribute($value){
        if( is_array($value) ){
            $this->attributes['status'] = $value['id'];
        }else{
            $this->attributes['status'] = $value;
        }
    }


    /**
     * Application Location Name Attribute - Get
     *
     * @return mixed
     */
    public function getApplicationLocationNameAttribute(){
        $center_id = $this->attributes['application_location'];

        $center = Code::category('pmn')->where('name',$center_id)->first();

        if($center){
            return $center->value;

        }else {
            return $center_id;
        }
    }


    /**
     * Url Update - Get
     *
     * @return string
     */
    public function getUrlUpdateAttribute(){
        $realm = app('Atlantis\View\Interfaces\Realm')->current();

        /** Return the update url */
        return route("advance.{$realm->name}.edit",array($this->uuid));
    }


    /**
     *
     * @return string
     */
    public function getPaymentProcessingStatusAttribute(){
        /** Default processing status : unavailable */
        $status = 'unavailable';

        /** Get transaction count */
        $transactions = $this->transaction()->where('transaction_type','advance:payment');

        if( $transactions->count() > 0 ){
            /** Get transaction */
            $transaction = $transactions->first();

            if( !empty($transaction->credit_account_id) ){
                /** Account number is generated : pending */
                $status = 'pending';

                if( isset($transaction->meta) ){
                    /** Account is exist : processing */
                    if( isset($transaction->meta->voucher_number) ) $status = 'processing';

                    /** Payment in sync, processing complete : complete */
                    if( isset($transaction->meta->sync) ){
                        if( $transaction->meta->sync == 1 ) $status = 'complete';
                    }
                }
            }
        }

        return $status;
    }


    /**
     * Override
     *
     * @return string
     */
    public function getCreatedWhenAttribute(){
        return Date::createFromTimeStamp(strtotime($this->created_at))->diffForHumans();
    }


    /**
     * Override
     *
     * @return string
     */
    public function getUpdatedWhenAttribute(){
        return Date::createFromTimeStamp(strtotime($this->updated_at))->diffForHumans();
    }


    /**
     * Scope Center
     *
     * @param $query
     * @param $center
     */
    public function scopeCenter($query,$center){
        $query->where('application_location',$center);
    }

}

modules/advance/views/cards/application.blade.php
<div class="wizard-input-section row">
    <div class="col-lg-6">
        {{ Former::text('amount_total')
            ->disabled()
            ->class('validate[required,custom[number],max['. $config['application']['amount_maximum'] .']]')
            ->ng_model('detail.amount_total')
            ->ng_disabled($conditions_disable['form'])
            ->as_ui_validation()
        }}
    </div>
    <div class="col-lg-6">
        {{ Former::text('account_no')
            ->class('validate[required,custom[number]]')
            ->ng_model('detail.user.profile.data.account_bank_no')
            ->ng_disabled($conditions_disable['form'])
            ->as_ui_validation()
        }}
    </div>
</div>
<div class="wizard-input-section">
    {{ Former::select('application_location')
        ->class('validate[required]')
        ->as_ui_validation()
        ->fromQuery( Code::category('pmn')->get(), function($model){return $model->value;}, 'name' )
        ->ng_model('detail.application_location')
        ->ng_disabled($conditions_disable['form'])
        ->ui_select2()
    }}
</div>
<div class="wizard-input-section">
    {{ Former::select('bank_code')
        ->class('validate[required]')
        ->as_ui_validation()
        ->fromQuery( Code::category('bank')->whereIn('name', $config['filters']['category_bank'] )->get(), function($model){return $model->value;}, 'name' )
        ->ng_model('detail.user.profile.data.account_bank_code')
        ->ng_disabled($conditions_disable['form'])
        ->ui_select2()
    }}
</div>
<div class="wizard-input-section row">
    <div class="col-lg-6">
        {{ Form::label(trans('advance::cards.section.application.existing')) }}
    </div>
    <div class="col-lg-3">
        <input type="radio" name="application_existing" value="1" ng-model="detail.application_existing" as-ui-icheck ng-disabled='{{$conditions_disable["form"]}}'>
        {{ Form::label('application_existing',trans('general.title.yes')) }}
        <input name="application_existing" type="hidden" class="validate[required]" ng-model="detail.application_existing" as_ui_validation>
    </div>
    <div class="col-lg-3">
        <input type="radio" name="application_existing" value="0" ng-model="detail.application_existing" as-ui-icheck ng-disabled='{{$conditions_disable["form"]}}'>
        {{ Form::label('application_existing',trans('general.title.no')) }}
    </div>
</div>

modules/advance/views/cards/approval.blade.php
<div class="panel" ng-controller="ApplicationApproval">
    <div class="panel-heading">
        {{ trans('advance::advance.title.application_approval') }}
    </div>
    <ul class="list-group" as-ui-card="approval">
        <li class="list-group-item">
            <div class="form-group">
                {{ Former::text('amount_total','amount_total')
                    ->class('form-control')
                    ->ng_disabled($conditions_disable['form'])
                    ->ng_model('detail.amount_total')
                    }}
            </div>
        </li>
        <li class="list-group-item">
            <div class="form-group">
                {{ Former::text('detail_amount_approved',trans('advance::advance.title.application_approval_amount'))
                    ->class('form-control validate[required,custom[number],min['. $config['application']['amount_minimum'] .'],max['. $config['application']['amount_maximum'] .']]')
                    ->ng_model('detail.amount_approved')
                    ->ng_disabled('detail.status.raw >= 7')
                    ->as_ui_validation()
                }}
            </div>
        </li>
        <li class="list-group-item">
            <btn id="btn-action-7"
                    class="action-status btn btn-{{ $detail->status['all'][7]['label'] }} ladda-button"
                    ng-click="approve()"
                    ng-show="{{ (isset($actions_conditions[$record->status['id']][7]) ? $actions_conditions[$record->status['id']][7] : true) }}"
                    ng-disabled="!validation.$error.cards.approval.$valid"
                    as-ui-button
                    as-ui-progress="ladda">
                {{ $detail->status['all'][7]['title'] }}
            </btn>
        </li>
    </ul>
</div>

@section('javascript')
    @parent
    <script language="JavaScript" type="text/javascript">
        var urlAPIAdvanceRecord = appBase + 'api/v1/advance/records/';

        asng.controller('ApplicationApproval',['$scope', 'Rpc', 'Validation', 'Model', function($scope, Rpc, Validation){
            /** Re-enable validation */
            Validation.config.validate = true;
            $scope.validation = Validation;

            /** Advance/Record RPC */
            $scope.record = Rpc.create('Advance/Record');

            $scope.approve = function(){
                $scope.record.execute('approve',{
                    uuid: $scope.detail.uuid,
                    amount_approved: $scope.detail.amount_approved
                }).success(function(response){
                    _a.alert.rpc(response).done(function(){
                        location.reload(true);
                    });
                });
            }
        }]);
    </script>
@stop

modules/advance/views/cards/course.blade.php
<div ng-controller="AdvanceCourse">
    <div class="wizard-input-section">
        @if( $user_realm->name == 'staff' )
        <div class="input-group">
        @endif
            {{ Former::text('application_coursed')
                ->class('validate[required]')
                ->ng_model('detail.application_coursed')
                ->ng_disabled($conditions_disable['form'])
                ->as_ui_validation()
            }}
        @if( $user_realm->name == 'staff' )
            <span class="input-group-btn">
                <button class="btn btn-primary btn-sm" ng-click="getCourse()"><i class="fa fa-search"> </i> Carian</button>
            </span>
        </div>
        @endif
    </div>
    <div class="wizard-input-section row">
        <div class="col-lg-9">
            @if( $user_realm->name == 'staff' )
            <div class="input-group">
            @endif
                {{ Former::text('institution_name')
                    ->class('validate[required]')
                    ->ng_model('detail.institution_name')
                    ->ng_disabled($conditions_disable['form'])
                    ->as_ui_validation()
                }}

            @if( $user_realm->name == 'staff' )
                <span class="input-group-btn">
                    <button class="btn btn-primary btn-sm" ng-click="getInstitutions()"><i class="fa fa-search"> </i> Carian</button>
                </span>
            </div>
            @endif
        </div>
        <div class="col-lg-3">
            {{ Former::select('institution_state')
                ->class('validate[required]')
                ->fromQuery( Code::category('state')->get(), function($model){return $model->value;}, 'name' )
                ->ng_model('detail.institution_state')
                ->ng_disabled($conditions_disable['form'])
                ->ui_select2()
            }}
        </div>
    </div>
    <div class="wizard-input-section">
        {{ Former::select('course_level')
            ->class('validate[required]')
            ->as_ui_validation()
            ->fromQuery( Code::category('course-level')->get(), function($model){return $model->value;}, 'name' )
            ->ng_model('detail.course_level')
            ->ng_disabled($conditions_disable['form'])
            ->ui_select2()
        }}
    </div>
    <div class="wizard-input-section row">
        <div class="col-lg-6">
            {{ Former::text('data_course_start',trans('advance::validation.attributes.course_start'))
                ->ng_model('data.course_start')
                ->ng_disabled($conditions_disable['form'])
                ->as_ui_datepicker('dd-mm-yy')
                ->as_ui_datepicker_options('{altField:"#course_start",altFormat:"yy-mm-dd",yearRange: "c:c+10"}')
            }}
            {{
                Former::text('course_start',false)
                ->class('hidden validate[required,custom[dateUS],future[NOW]]')
                ->ng_model('detail.course_start')
                ->as_ui_validation();
            }}
        </div>
        <div class="col-lg-6">
            {{ Former::text('data_course_end',trans('advance::validation.attributes.course_end'))
                ->ng_model('data.course_end')
                ->ng_disabled($conditions_disable['form'])
                ->as_ui_datepicker('dd-mm-yy')
                ->as_ui_datepicker_options('{altField:"#course_end",altFormat:"yy-mm-dd",yearRange: "c:c+10"}')
            }}
            {{
                Former::text('course_end',false)
                ->class('hidden validate[required,custom[dateUS],future[#data_course_end_on]]')
                ->ng_model('detail.course_end')
                ->as_ui_validation();
            }}
            <input type="hidden" id="data_course_end_on" name="data_course_end_on" ng-bind="data.courseEndOn()">
        </div>
    </div>
    <div class="wizard-input-section">
        <button class="btn btn-primary" onclick="$('[href=#documents]').tab('show');">Upload Document</button>
    </div>
    @include('advance::partials.code-lookup')
</div>

@section('javascript')
    @parent
    <script language="JavaScript" type="text/javascript">
        var url = appBase + 'api/v1/codes/institution-name?format=list';

        /**
         * Temporary date validation alert workaround
         */
        $.validationEngineLanguage.allRules.dateUS.alertText = $.validationEngineLanguage.allRules.date.alertText

        asng.controller('AdvanceCourse', ['$scope','$http','$modal', function($scope,$http,$modal){
            /** Transactional data */
            $scope.data = {
                courseEndOn: function(){
                    var dateEnd = moment($scope.detail.course_start,'YYYY-MM-DD').add(18,'month').format('YYYY-MM-DD');
                    $('#data_course_end_on').val(dateEnd);
                    return dateEnd;
                }
            };

            /** Course name lookup dialog */
            $scope.getCourse = function(){
                $scope.params = {
                    title: 'Carian Kursus',
                    search_key_label: 'Nama Kursus',
                    code_category: 'course-name'
                };

                var codeLookupModal = $modal.open({
                    templateUrl: 'CodeLookuplModal.html',
                    controller: 'CodeLookuplModal',
                    size: '',
                    resolve: {
                        params: function(){
                            return $scope.params;
                        }
                    }
                });

                codeLookupModal.result.then(function (code) {
                    $scope.detail.application_coursed = code.value;
                });
            };

            /** Institution lookup dialog */
            $scope.getInstitutions = function(){
                $scope.params = {
                    title: 'Carian Institusi',
                    search_key_label: 'Nama Institusi',
                    code_category: 'institution-name'
                };

                var codeLookupModal = $modal.open({
                    templateUrl: 'CodeLookuplModal.html',
                    controller: 'CodeLookuplModal',
                    size: '',
                    resolve: {
                        params: function(){
                            return $scope.params;
                        }
                    }
                });

                codeLookupModal.result.then(function (code) {
                    $scope.detail.institution_name = code.value;
                });
            };

        }]);
    </script>
@stop

modules/advance/views/cards/documents.blade.php
<div class="panel">
    <div class="panel-heading">
        {{ trans('advance::advance.title.document_approved') }}
    </div>
    <ul class="list-group">
        @if( $user_realm->name == 'staff' )
        <li class="list-group-item">
            <div class="form-group">
                <label> No Akaun Pelajar :</label>
                <div class="well"><h3 style="margin: 0; text-align: center;">{{ $record->transaction->credit_account_id or 'Tiada' }}</h3></div>
            </div>
            <div class="form-group">
                <label> Status Pembayaran :</label>
                <div class="alert alert-{{ $record->payment_processing_status == 'complete' ? 'success' : 'warning' }}">{{ trans('advance::advance.status.payment.'.$record->payment_processing_status) }}</div>
            </div>
        </li>
        @endif
        <a class="list-group-item list-group-item-success" href="{{ url('documents/download'.'?name=approval&uuid='.$record->uuid) }}">
            {{ trans('advance::advance.documents.offer_letter') }}
            <div class="pull-right action-buttons">
                <i class="icon icon-cloud-download text-success"></i>
            </div>
        </a>
        <a class="list-group-item list-group-item-success" href="{{ url('assets/documents/agreement.pdf') }}">
            {{ trans('advance::advance.documents.agreement_letter') }}
            <div class="pull-right action-buttons">
                <i class="icon icon-cloud-download text-success"></i>
            </div>
        </a>
        <a class="list-group-item list-group-item-success" href="{{ url('documents/download'.'?name=application&uuid='.$record->uuid) }}">
            {{ trans('advance::advance.documents.applicant_info') }}
            <div class="pull-right action-buttons">
                <i class="icon icon-cloud-download text-success"></i>
            </div>
        </a>
    </ul>
</div>

modules/advance/views/cards/final.blade.php
{{ Former::open() }}
<div class="wizard-input-section">
    <p>{{ trans('advance::cards.section.final.terms_title') }}</p>
    <textarea rows="6" placeholder="{{ trans('advance::cards.section.final.terms_title') }}">{{ trans('advance::cards.section.final.terms_body') }}</textarea>
</div>
<div class="wizard-input-section">
    {{ Former::input('final')
        ->type('checkbox')
        ->as_ui_icheck()
        ->ng_model('final')
        ->ng_disabled($conditions_disable['form'])
    }}
    {{ Former::label(trans('advance::cards.section.final.checkbox_final')) }}
</div>
{{ Former::close() }}

modules/advance/views/cards/guarantor.blade.php
<div ng-controller="AdvanceGuarantor">
    <div class="wizard-input-section row">
        <div class="col-lg-8">
            {{ Former::text('guarantor_id')
                ->class('validate[required,custom[idICNo]]')
                ->ng_model('detail.guarantor.idno_ic')
                ->ng_model_options('{debounce:500}')
                ->ng_keyup('checkGuarantor($event)')
                ->ng_disabled($conditions_disable['form'])
                ->as_ui_validation()
            }}
        </div>
        <div class="col-lg-4" style="padding-top: 23px;">
            <input type="checkbox" name="is_guardian" value="1" as-ui-icheck ng-model="is_guardian" ng-change="isGuardian()" ng-checked="validation.cards.guardian[0].$valid && validation.cards.guarantor[0].$valid">
            {{ Form::label('is_guardian','Penjamin adalah penjaga') }}
        </div>
    </div>

    <div class="wizard-input-section row">
        <div class="col-lg-6">
            {{ Former::text('guarantor[first_name]',trans('advance::cards.section.guarantor.first_name'))
                ->ng_model('detail.guarantor.first_name')
                ->ng_disabled($conditions_disable['form'])
                ->class('validate[required]')
                ->as_ui_validation()
            }}
        </div>
        <div class="col-lg-6">
            {{ Former::text('guarantor[last_name]',trans('advance::cards.section.guarantor.last_name'))
                ->ng_model('detail.guarantor.last_name')
                ->ng_disabled($conditions_disable['form'])
                ->class('validate[required]')
                ->as_ui_validation()
            }}
        </div>
    </div>

    <div class="wizard-input-section">
        {{ Former::text('guarantor[address_street]',trans('advance::cards.section.guarantor.address_street'))
            ->ng_model('detail.guarantor.address_street')
            ->ng_disabled($conditions_disable['form'])
            ->class('validate[required]')
            ->as_ui_validation()
        }}
    </div>

    <div class="wizard-input-section row">
        <div class="col-lg-6">
            {{ Former::text('guarantor[address_district]',trans('advance::cards.section.guarantor.address_district'))
                ->ng_model('detail.guarantor.address_district')
                ->ng_disabled($conditions_disable['form'])
                ->class('validate[required]')
                ->as_ui_validation()
            }}
        </div>
        <div class="col-lg-6">
            {{ Former::text('guarantor[address_city]',trans('advance::cards.section.guarantor.address_city'))
                ->ng_model('detail.guarantor.address_city')
                ->ng_disabled($conditions_disable['form'])
                ->class('validate[required]')
                ->as_ui_validation()
            }}
        </div>
    </div>

    <div class="wizard-input-section row">
        <div class="col-lg-8">
            {{ Former::select('guarantor[address_state]',trans('advance::cards.section.guarantor.address_state'))
                ->class('validate[required]')
                ->as_ui_validation()
                ->ng_model('detail.guarantor.address_state')
                ->ng_disabled($conditions_disable['form'])
                ->fromQuery( Code::category('state')->get(), function($model){return $model->value;}, 'name' )
                ->ui_select2()
            }}
        </div>
        <div class="col-lg-4">
            {{ Former::text('guarantor[address_postcode]',trans('advance::cards.section.guarantor.address_postcode'))
                ->ng_model('detail.guarantor.address_postcode')
                ->ng_disabled($conditions_disable['form'])
                ->class('validate[required,custom[postcode]]')
                ->as_ui_validation()
            }}
        </div>
    </div>

    <div class="wizard-input-section row">
        <div class="col-lg-6">
            {{ Former::text('guarantor[contact_home]',trans('advance::cards.section.guarantor.contact_home'))
                ->ng_model('detail.guarantor.contact_home')
                ->ng_disabled($conditions_disable['form'])
                ->class('validate[custom[number]]')
                ->as_ui_validation()
            }}
        </div>
        <div class="col-lg-6">
            {{ Former::text('guarantor[contact_mobile]',trans('advance::cards.section.guarantor.contact_mobile'))
                ->ng_model('detail.guarantor.contact_mobile')
                ->ng_disabled($conditions_disable['form'])
                ->class('validate[required,custom[number]]')
                ->as_ui_validation()
            }}
        </div>
    </div>

    <div class="wizard-input-section row">
        <div class="col-lg-8">
            {{ Former::text('guarantor_salary_gross',trans('advance::cards.section.guarantor.guarantor_salary_gross'))
                ->ng_model('detail.guarantor_salary_gross')
                ->ng_disabled($conditions_disable['form'])
                ->class('validate[required,custom[number],min['. $config['application']['salary_guarantor_min'] .']]')
                ->as_ui_validation()
            }}
        </div>
        <div class="col-lg-4">
            {{ Former::select('guarantor_status')
                ->ng_model('detail.guarantor_status')
                ->ng_disabled($conditions_disable['form'])
                ->options(array(
                    1 => trans('advance::cards.section.guarantor.guarantor_status_parent'),
                    2 => trans('advance::cards.section.guarantor.guarantor_status_not_parent')
                ))
                ->ui_select2()
            }}
        </div>
    </div>
</div>

@section('javascript')
    @parent
    <script language="JavaScript" type="text/javascript">

        asng.controller('AdvanceGuarantor', ['$scope','Rest',function($scope, Rest){
            /** Globals */
            var curScope = $scope;

            /** Check for blacklist */
            $scope.checkGuarantor = function(elem){
                var elementInput = $(elem.target);

                if( !elementInput.validationEngine('validate') ){
                    var idNoIc = elementInput.val();

                    $.getJSON(urlAPIPeople + 'search',{idno_ic:idNoIc}, function(data){
                        if( data.blacklist === 1 ){
                            var modal_body = '{{ trans("advance::advance.blacklist.modal-body") }}';
                            modal_body = modal_body.replace(':idno_ic',idNoIc);

                            BootstrapDialog.show({
                                type: BootstrapDialog.TYPE_WARNING,
                                message: modal_body,
                                onhide: function(dialogRef){
                                    elementInput.val('');
                                }
                            });

                        }else if( data.id ){
                            curScope.getGuarantor(data.id);

                        }else{
                            curScope.detail.guarantor_id = '';
                        }
                    });
                }
            };

            /** Attach guarantor detail */
            $scope.getGuarantor = function(guarantorId){
                $scope.detail.guarantor_id = guarantorId;
                $scope.detail.guarantor = Rest.get({model:'peoples', id:guarantorId});
            };


            $scope.isGuardian = function(){
                if( $scope.is_guardian ){
                    $scope.updateDetail(function(){
                        $scope.getGuarantor($scope.detail.guardian_id);
                        $scope.detail.guarantor_salary_gross = $scope.detail.guardian_salary_gross;
                    });
                }
            }
        }]);

    </script>
@stop

modules/advance/views/cards/voucher.blade.php
<div class="panel" ng-controller="PaymentVoucher">
    <div class="panel-heading">
        {{ trans('advance::advance.title.application_payment') }}
    </div>
    <ul class="list-group" as-ui-card="voucher">
        <li class="list-group-item">
            <div class="form-group">
                <label> No Kelulusan :</label>
                <div class="well"><h3 style="margin: 0; text-align: center;">{{ $record->transaction->credit_account_id or 'Tiada' }}</h3></div>
            </div>
            <div class="form-group">
                <label> Status Pembayaran :</label>
                <div class="alert alert-{{ $record->payment_processing_status == 'complete' ? 'success' : 'warning' }}">{{ trans('advance::advance.status.payment.'.$record->payment_processing_status) }}</div>
            </div>
        </li>
        @if($record->transaction->credit_account_id)
        <li class="list-group-item">
            <div class="form-group">
                {{ Former::text('voucher_number')
                    ->class('form-control validate[required]')
                    ->ng_disabled($record->payment_processing_status == 'complete' ? 1 : 0)
                    ->ng_model('detail.transaction.meta.voucher_number')
                    ->as_ui_validation() }}

            </div>
            <div class="form-group">
                {{ Former::text('cheque_number')
                    ->class('form-control validate[required]')
                    ->ng_disabled($record->payment_processing_status == 'complete' ? 1 : 0)
                    ->ng_model('detail.transaction.meta.cheque_number')
                    ->as_ui_validation() }}
            </div>
            <div class="form-group">
                {{ Former::text('cheque_date')
                    ->class('form-control validate[required]')
                    ->ng_disabled($record->payment_processing_status == 'complete' ? 1 : 0)
                    ->ng_model('detail.transaction.meta.cheque_date')
                    ->as_ui_datepicker('dd-mm-yy') }}
            </div>
        </li>
        <li class="list-group-item">
            <button class="btn btn-success" ng-click="payment()" ng-disabled="!validation.$error.cards.voucher.$valid || {{ $record->payment_processing_status == 'complete' ? 1 : 0 }}">{{ trans('general.title.update') }}</button>
            <a class="btn btn-primary" ng-disabled="{{ $record->payment_processing_status == 'complete' || $record->payment_processing_status == 'processing' ? true : false }}" href="{{ url('documents/download'.'?name=voucher&uuid='.$record->uuid) }}">{{ trans('general.title.print') }}</a>
        </li>
        @endif
    </ul>
</div>

@section('javascript')
    @parent
    <script language="JavaScript" type="text/javascript">
        var urlAPIAdvanceRecord = appBase + 'api/v1/documents/';

        asng.controller('PaymentVoucher',['$scope', 'Rpc', 'Validation', function($scope, Rpc, Validation){
            /** Re-enable validation */
            Validation.config.validate = true;
            $scope.validation = Validation;

            /** Advance/Record RPC */
            $scope.record = Rpc.create('Advance/Record');

            $scope.payment = function(){
                $scope.record.execute('payment',{
                    uuid: $scope.detail.uuid,
                    voucher_number: $scope.detail.transaction.meta.voucher_number,
                    cheque_number: $scope.detail.transaction.meta.cheque_number,
                    cheque_date: $scope.detail.transaction.meta.cheque_date
                }).success(function(response){
                    _a.alert.rpc(response).done(function(){
                        location.reload(true);
                    });
                });
            }
        }]);
    </script>
@stop