modules/advance/models/Album.php
<?php


class Album extends \Eloquent {
    protected $table = 'Albmas';
    protected $connection = 'mysql_album';
    protected $primaryKey = 'NOMBOR_GAJI';


    public function getSalaryIdAttribute(){
        return $this->attributes['NOMBOR_GAJI'];
    }
    public function setSalaryIdAttribute($value){
        $this->attributes['NOMBOR_GAJI'] = $value;
    }


    public function getNameAttribute(){
        return $this->attributes['NAMA'];
    }
    public function setNameAttribute($value){
        $this->attributes['NAMA'] = $value;
    }


    public function getSalaryGradeAttribute(){
        return $this->attributes['GRED_GAJI'];
    }
    public function setSalaryGradeAttribute($value){
        $this->attributes['GRED_GAJI'] = $value;
    }


    public function getIdnoIcAttribute(){
        return $this->attributes['NO_K/P'];
    }
    public function setIdnoIcAttribute($value){
        $this->attributes['NO_K/P'] = $value;
    }


    public function getCenterIdAttribute(){
        return $this->attributes['KOD_PUSAT'];
    }
    public function setCenterIdAttribute($value){
        $this->attributes['KOD_PUSAT'] = $value;
    }
}

modules/advance/views/staff/browse.blade.php
@extends('themes/default::layouts.fluid')

@section('base')
<div class="main-content">
    @include('advance::partials.header-sub')
    <div class="container" ng-controller="controllerDetails">
        @include('core::partials.error')
        <div class="row">
            <div class="col-lg-9">
                <div class="row">
                </div>
                <div class="box">
                    <div class="box-header border-bottom-off">
                        <span class="title">{{ trans('advance::advance.title.student_manage') }}</span>
                    </div>
                    <div class="box-content">
                        <table id="details-manage" as-ui-table as-ui-table-options="table_options" ao-column-defs="table_columns" class="responsive">
                            <thead>
                            <tr>
                                <th style="width:150px"><div>{{ trans('advance::advance.title.application_date') }}</div></th>
                                <th style="width:120px"><div>{{ trans('advance::validation.attributes.idno_ic') }}</div></th>
                                <th><div>{{ trans('advance::advance.title.student_name') }}</div></th>
                                <th style="width:100px"><div>{{ trans('advance::advance.title.application_status') }}</div></th>
                                <th style="width:200px"><div>{{ trans('advance::advance.title.application_location') }}</div></th>
                            </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="box">
                    <div class="box-header">
                        <span class="title">{{ trans('general.title.search') }}</span>
                    </div>
                    <div class="box-content padded">
                        <form class="fill-up">
                            <div class="form-group">
                                {{ Former::select('application_location')
                                    ->fromQuery( Code::category('pmn')->get(), function($model){return $model->value;}, 'name' )
                                    ->ng_model('application_location')
                                    ->ui_select2()
                                    ->as_ui_table_filters()
                                }}
                            </div>
                            <div class="form-group">
                                {{ Former::text('first_name')
                                    ->class('form-control')
                                    ->ng_model('user.first_name')
                                    ->as_ui_table_filters()
                                }}
                            </div>
                            <div class="form-group">
                                {{ Former::text('idno_ic')
                                    ->class('form-control')
                                    ->ng_model('user.profile.idno_ic')
                                    ->as_ui_table_filters()
                                }}
                            </div>
                            @if( isset($status['all']) )
                            <div class="form-group">
                                {{ Former::select('status')
                                    ->fromQuery( $status['all'], 'title', 'id' )
                                    ->ng_model('status')
                                    ->ui_select2()
                                    ->as_ui_table_filters()
                                }}
                            </div>
                            @endif
                        </form>
                        <btn class="btn btn-xs btn-default" ng-click="resetFilter()">{{ trans('general.title.reset') }}</btn>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('javascript')
    @parent
    <script language="JavaScript" type="text/javascript">
        function controllerDetails($scope){
            $scope.filterDefault = function(){
                $scope.$eval("application_location = ''");
                $scope.$eval("user.first_name = ''");
                $scope.$eval("user.profile.idno_ic = ''");
                $scope.status = '';
            };
            $scope.filterDefault();

            $scope.table_options = {
                "sPaginationType": "full_numbers",
                "sDom": '<"">tr<"table-footer"ip>',
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": appBase + 'api/v1/details',
                "aDefaultFilters": []
            };

            $scope.table_columns = [
                {"aTargets":[0],'mData':'created_at','sType':'date'},
                {"aTargets":[1],'mData':'user.profile.idno_ic'},
                {"aTargets":[2],'mData':'user.full_name'},
                {"aTargets":[3],'mData':'status','mRender':function(data, type, full){
                    return '<span class="label label-' + data['label'] + '">' + data['title'] + '</span>';
                }},
                {"aTargets":[4],'mData':'application_location_name'}
            ];

            $scope.resetFilter = function(){
                $scope.filterDefault();
                $scope.asTableReset('details-manage');
            }
        }
    </script>
@stop

modules/advance/views/staff/detail.blade.php
@extends('themes/default::layouts.fluid')

@section('base')
<div class="main-content">
    <div class="container" ng-controller="controllerDetail">
        @include('core::partials.error')
        <div class="row">
            <div class="area-top clearfix">
                <div class="pull-left header">
                    <h3 class="title">
                        <i class="fa fa-tasks"></i> {{ $detail->description }}
                    </h3>
                    <h5>
                        <span class="visible-lg">
                            <span class="label label-{{ $record->status['label'] }}">{{ $record->status['title'] }}</span>
                            <span>{{ trans('general.title.created_at').' '.$record->created_when }}, </span>
                            <span>{{ trans('general.title.updated_at').' '.$record->updated_at->formatLocalized('%A, %d %B %Y') }}</span>
                        </span>
                    </h5>
                </div>
            </div>
        </div>

        <div class="row padded">
            <ul class="row nav nav-tabs nav-tabs-left" style="padding-left:15px;">
                <li class="active"><a href="#home" data-toggle="tab"><i class="fa fa-home"></i> <span>{{ trans('advance::advance.title.detail_form') }}</span></a></li>
                <li><a href="#documents" data-toggle="tab"><i class="fa fa-file"></i> <span>{{ trans('advance::cards.title.document') }}</span></a></li>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="tab-content">
                    <!-- ------------------------------------------------
                        Tab Home
                    -->
                    <div id="home" class="tab-pane active">
                        @include('advance::partials.box')
                    </div>
                    <!-- ------------------------------------------------
                        Tab Document
                    -->
                    <div id="documents" class="tab-pane">
                        @include('advance::staff.partials.document')
                    </div>
                </div>
                @include('advance::partials.compose')
            </div>
            <div class="col-md-4">
                @if( $record->status['raw'] == 4 )
                    @include('advance::cards.approval')
                @endif
                @if( $record->status['raw'] == 7 )
                    @include('advance::cards.documents')
                @endif
                @include('advance::partials.conversations')
            </div>
        </div>
    </div>
</div>
@stop

@section('javascript')
    @parent
    <script language="JavaScript" type="text/javascript">
        var urlAPIPeople = appBase + 'api/v1/peoples/';
        var urlAPIDocument = appBase + 'api/v1/documents/';

        function controllerDetail($scope,Rest,Validation){
            //i: Variables
            $scope.validation = Validation;
            $scope.detail_params = {model:'details', id:'{{ (isset($record) ? $record->uuid : "") }}'};

            //i: Getting detail model
            $scope.detail = Rest.get($scope.detail_params);

            //i: Attach guardian detail
            $scope.getGuardian = function(guardianId){
                $scope.detail.guardian_id = guardianId;
                $scope.detail.guardian = Rest.get({model:'peoples', id:guardianId});
            }

            //i: Attach guarantor detail
            $scope.getGuarantor = function(guarantorId){
                $scope.detail.guarantor_id = guarantorId;
                $scope.detail.guarantor = Rest.get({model:'peoples', id:guarantorId});
            }

            $scope.$watchCollection($scope.validation.$error.cards, function(){
                $scope.boxes = angular.copy($scope.validation.$error.cards);
            })
        }
    </script>
@stop

modules/advance/views/staff/details.blade.php
@extends('themes/default::layouts.fluid')

@section('base')
<div class="main-content">
    @include('advance::partials.header-sub')
    <div class="container" ng-controller="controllerDetails">
        @include('core::partials.error')
        <div class="row">
            <div class="col-lg-9">
                <div class="row">
                </div>
                <div class="box">
                    <div class="box-header border-bottom-off">
                        <span class="title">{{ trans('advance::advance.title.student_manage') }}</span>
                    </div>
                    <div class="box-content">
                        <table id="details-manage" as-ui-table as-ui-table-options="table_options" ao-column-defs="table_columns" class="responsive">
                            <thead>
                            <tr>
                                <th style="width:150px"><div>{{ trans('advance::advance.title.application_date') }}</div></th>
                                <th style="width:150px"><div>{{ trans('advance::validation.attributes.idno_ic') }}</div></th>
                                <th><div>{{ trans('advance::advance.title.student_name') }}</div></th>
                                <th style="width:100px"><div>{{ trans('advance::advance.title.application_status') }}</div></th>
                                <th style="width:40px">{{ trans('advance::advance.title.action') }}</th>
                            </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="box">
                    <div class="box-header">
                        <span class="title">{{ trans('general.title.search') }}</span>
                    </div>
                    <div class="box-content padded">
                        <form class="fill-up">
                            <div class="form-group">
                                {{ Former::select('application_location')
                                    ->fromQuery( Code::category('pmn')->get(), function($model){return $model->value;}, 'name' )
                                    ->disabled(!User::find($user->id)->hasRole('Pentadbir Sistem'))
                                    ->ng_model('application_location')
                                    ->ui_select2()
                                    ->as_ui_table_filters()
                                }}
                            </div>
                            <div class="form-group">
                                {{ Former::text('first_name')
                                    ->class('form-control')
                                    ->ng_model('user.first_name')
                                    ->as_ui_table_filters()
                                }}
                            </div>
                            <div class="form-group">
                                {{ Former::text('idno_ic')
                                    ->class('form-control')
                                    ->ng_model('user.profile.idno_ic')
                                    ->as_ui_table_filters()
                                }}
                            </div>
                            @if( count($status_role) > 0 )
                            <div class="form-group">
                                {{ Former::select('status')
                                    ->fromQuery( $status_role, 'title', 'id' )
                                    ->ng_model('status')
                                    ->ui_select2()
                                    ->as_ui_table_filters()
                                }}
                            </div>
                            @endif
                        </form>
                        <btn class="btn btn-xs btn-default" ng-click="resetFilter()">{{ trans('general.title.reset') }}</btn>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('javascript')
    @parent
    <script language="JavaScript" type="text/javascript">
        function controllerDetails($scope){
            //i: Initial filter value
            $scope.filterDefault = function(){
                $scope.application_location = '{{  User::find($user->id)->profile->data->center_id }}';
                $scope.$eval("user.first_name = ''");
                $scope.$eval("user.profile.idno_ic = ''");
                $scope.status = '{{ array_values($status_role)[0]["id"] }}';
            };
            $scope.filterDefault();

            $scope.table_options = {
                "sPaginationType": "full_numbers",
                "sDom": '<"">tr<"table-footer"ip>',
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": appBase + 'api/v1/details',
                "aDefaultFilters": ['status','application_location']
            };

            $scope.table_columns = [
                {"aTargets":[0],'mData':'created_at','sType':'date'},
                {"aTargets":[1],'mData':'user.profile.idno_ic'},
                {"aTargets":[2],'mData':'user.full_name'},
                {"aTargets":[3],'mData':'status','mRender':function(data, type, full){
                    return '<span class="label label-' + data['label'] + '">' + data['title'] + '</span>';
                }},
                {"aTargets":[4],'mData':'url_update','mRender':function(data, type, full){
                    return '<a href="' + data + '{{ isset($mode) ? "/{$mode}" : '' }}"><i class="fa fa-cog"></i></a>';
                }}
            ];

            $scope.resetFilter = function(){
                $scope.filterDefault();
                $scope.asTableReset('details-manage');
            }
        }
    </script>
@stop

modules/advance/views/staff/payment.blade.php
@extends('themes/default::layouts.fluid')

@section('stylesheet')
    @parent
    <style>
        form.plain textarea,
        form.plain input[type="text"],
        form.plain input[type="password"],
        form.plain input[type="datetime"],
        form.plain input[type="datetime-local"],
        form.plain input[type="date"],
        form.plain input[type="month"],
        form.plain input[type="time"],
        form.plain input[type="week"],
        form.plain input[type="number"],
        form.plain input[type="email"],
        form.plain input[type="url"],
        form.plain input[type="search"],
        form.plain input[type="tel"],
        form.plain input[type="color"],
        form.plain select,
        form.plain .uneditable-input,
        form.plain .select2-container .select2-choice,
        form.plain .select2-container.select2-container-disabled .select2-choice {
            background: none;
            border-width: 0 0 1px 0;
            border-style: dotted;
        }

        form.plain .select2-container.select2-container-disabled .select2-choice div {
            display: none;
        }
    </style>
@stop

@section('base')
<div class="main-content">
    <div class="container" ng-controller="controllerDetail">
        @include('core::partials.error')
        <div class="row">
            <div class="area-top clearfix">
                <div class="pull-left header">
                    <h3 class="title">
                        <i class="fa fa-tasks"></i> {{ $detail->description }}
                    </h3>
                    <h5>
                        <span class="visible-lg">
                            <span class="label label-{{ $record->status['label'] }}">{{ $record->status['title'] }}</span>
                            <span>{{ trans('general.title.created_at').' '.$record->created_when }}, </span>
                            <span>{{ trans('general.title.updated_at').' '.$record->updated_at->formatLocalized('%A, %d %B %Y') }}</span>
                        </span>
                    </h5>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8">
                <div class="panel">
                    <div class="panel-heading">
                        {{ trans('advance::cards.title.application') }}
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <form name="info" class="plain form-horizontal fill-up" novalidate>
                            @include('advance::cards.profile')
                            </form>
                        </li>
                        <li class="list-group-item">
                            <form name="application" class="plain form-horizontal fill-up" novalidate>
                                @include('advance::cards.application')
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                @include('advance::cards.voucher')
            </div>
        </div>
    </div>
</div>
@stop

@section('javascript')
    @parent
    <script language="JavaScript" type="text/javascript">
        var urlAPIPeople = appBase + 'api/v1/peoples/';
        var urlAPIDocument = appBase + 'api/v1/documents/';

        function controllerDetail($scope,Rest,Validation){
            /** Disable validation for current view */
            Validation.config.validate = false;

            /** Record params */
            $scope.detail_params = {model:'details', id:'{{ (isset($record) ? $record->uuid : "") }}'};

            /** Getting detail model */
            $scope.detail = Rest.get($scope.detail_params);
        }
    </script>
@stop

modules/advance/views/staff/statistic.blade.php
@extends('themes/default::layouts.fluid')

@section('stylesheet')
    @parent
    <style>
        .packery {
            /*background: #FDD;
            background: hsla(45, 100%, 40%, 0.2);*/
        }

        /* clearfix */
        .packery:after {
            content: ' ';
            display: block;
            clear: both;
        }

        .item,
        .grid-sizer {
            width: 30%;
        }

        .item {
            height: 110px;
            /*float: left;
            background: #C09;
            border: 4px solid #333;
            border-color: hsla(0, 0%, 0%, 0.3);*/
        }

        .item.w2 { width:  62%; }
        .item.h2 { height: 220px; }
        .item.h4 { height: 440px; }
        .item.w4 { width: 120%; }

        .item.bg-success { background: #b6dd69; color: #779148; }
        .item.bg-info { background: #dee8f2; color: #3c6a95; }
        .item.bg-warning { background: #f8e9bb; color: #a37f11; }
        .item.bg-error { background: #ecb5ac; color: #c75d5d; }

        .item.bg-info .stats-label { color: #3c6a95; }
        .item.bg-warning .stats-label { color: #a37f11; }
        .item.bg-success .stats-label { color: #779148; }
        .item.bg-error .stats-label { color: #c75d5d; }
    </style>
@stop

@section('base')
<div class="main-content">
    @include('advance::partials.header-sub')
    <div class="container " ng-controller="controllerStatistic">
        @include('core::partials.error')
        <div class="row">

            <div class="col-md-6">
                <div class="box">
                    <div class="box-content">
                        <table class="table table-normal">
                            <thead>
                                <tr>
                                    <td>{{ trans('advance::advance.title.application_status') }}</td>
                                    <td>{{ trans('advance::advance.title.information') }}</td>
                                    <td>{{ trans('advance::advance.title.total') }}</td>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach( $statistics as $statistic )
                                <tr>
                                    <td style="width: 80px;"><span class="label label-{{ $statistic['status_label'] }}">{{ $statistic['status'] }}</span></td>
                                    <td>{{ $statistic['title'] }}</td>
                                    <td>{{ $statistic['value'] }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="packery js-packery" data-packery-options='{ "columnWidth": ".grid-sizer", "itemSelector": ".item", "gutter": 10 }'>
                    <div class="grid-sizer"></div>
                    @foreach( $statistics as $statistic )
                    <div class="box item {{ $statistic['class'] }}" style="margin-bottom: 0;">
                        <div class="box-content padded">
                            <div class="dashboard-stats">
                                <ul class="list-inline">
                                    <li class="glyph"><i class="fa fa-2x fa-user"></i></li>
                                    <li class="count">{{ $statistic['value'] }}</li>
                                </ul>
                                <div class="stats-label">{{ $statistic['title'] }}</div>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('javascript')
    @parent
    <script language="JavaScript" type="text/javascript">
        var urlAPIPeople = appBase + 'api/v1/peoples/';
        var urlAPIDocument = appBase + 'api/v1/documents/';

        function controllerStatistic($scope,Rest,Validation){

        }
    </script>
@stop